name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Ajusta la versión de Node.js si es necesario

    - name: Install dependencies
      run: npm ci

    - name: Run npm Audit for Security Vulnerabilities
      run: npm audit --audit-level=high

    - name: Run Lint
      run: npm run lint

    - name: Run Unit and Integration Tests
      run: npm test

    - name: Run E2E Tests
      run: npm run test:e2e
